name: nofrillsacademy
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: asset/fonts/OpenSans-Regular.ttf
          weight: 500
        - asset: asset/fonts/OpenSans-ExtraBold.ttf
          weight: 600
    # Uncomment and modify if you are using the Mont font
    # - family: Mont
    #   fonts:
    #     - asset: assets/fonts/Mont-HeavyDemo.otf
    #       weight: 700
